### PR TITLE
fixed client reboot issue

### LINKED ISSUE #72: Client restarts when logged in
This is a known issue. It is caused because of race condition in this code -
```
for i in $(seq 1 9); do
(
    nbd-client server -N /opt/ltsp/i386 /dev/nbd$i
    nbd-client -d /dev/nbd$i
) &
done
```
reference - https://github.com/NetworkBlockDevice/nbd/issues/59
Since ltsp now uses nbd sometimes it affects the ltsp setup. There is no error message to tell what is happening so I did `tail -f /var/log/syslog` on the server. And this was the output when I boot from the client
```
Jul  1 20:34:57 ubuntu-bionic nbd_server[1273]: Spawned a child process
Jul  1 20:34:57 ubuntu-bionic nbd_server[2335]: virtstyle ipliteral
Jul  1 20:34:57 ubuntu-bionic nbd_server[2335]: connect from 192.168.111.108, assigned file is /opt/ltsp/images/amd64.img
Jul  1 20:34:57 ubuntu-bionic nbd_server[2335]: Can't open authorization file /etc/ltsp/nbd-server.allow (No such file or directory).
Jul  1 20:34:57 ubuntu-bionic nbd_server[2335]: Size of exported file/device is 485146624
Jul  1 20:34:57 ubuntu-bionic nbd_server[2335]: Starting to serve
```
The client after login just restarts and brings back the login screen.
I know how to fix this one.

### PR DESCRIPTION
**Pull request by d78ui98**
closes #72

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -26,6 +26,10 @@ echo 'IPAPPEND=3' >> /etc/ltsp/update-kernels.conf
 # Configure dnsmasq
 ltsp-config dnsmasq
 
+# Client reboot issue fix
+echo 'INIT_COMMAND_RM_NBD_CHECKUPDATE="rm -rf /usr/share/ldm/rc.d/I01-nbd-checkupdate"' \
```
Comment (akash0x53) [inline install.sh]: Do not use `-r` if you're deleting file. I would suggest to move file to `I01-nbd-checkupdate.orig`  instead removing it.

Comment (d78ui98) [reply install.sh]: okay. Good idea.

**Review by akash0x53 — DISMISSED** [review]

File: install.sh [hunk 2]
```diff
@@ -26,6 +26,11 @@ echo 'IPAPPEND=3' >> /etc/ltsp/update-kernels.conf
 # Configure dnsmasq
 ltsp-config dnsmasq
 
+# Client reboot issue fix
```
Comment (akash0x53) [inline install.sh]: Just mention which issue we are fixing with this. Issue link would be great.

**Review by akash0x53 — APPROVED** [review]
