### PR TITLE
fixed client login problem

### LINKED ISSUE #34: Install LTSP in Debian with Vagrant
Will refer to here http://dashohoxha.fs.al/ltsp-pnp/
to install LTSP in debian `buster` with vagrant

### PR DESCRIPTION
**Pull request by d78ui98**
made some changes in `install.sh` to properly configure `sshd_config` file.

fixes #34

### CODE REVIEW

**Comment by d78ui98** [comment]
I have tested it multiple time. Also tested it on a friends laptop today.

File: client.sh [hunk 1]
```diff
@@ -13,41 +13,49 @@ cat <<-END
...
 
 if [ "$1" == "" ]; then
-  create_client
+    create_client
 fi
 
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-  usage
+    usage
 fi
```
Comment (dashohoxha) [inline client.sh]: - [x] Remove the help code.
 - [x] Get the name of the client as the first argument from the command line.
 - [x] If no client name is given as argument, use a default name.

File: client.sh [hunk 2]
```diff
@@ -13,41 +13,49 @@ cat <<-END
...
+    echo -n "Enter any name for LTSP client : "
+    read clientname
+    echo "Using ${INTERFACE}.."	
+    VBoxManage createvm --name "${clientname}" --register
+    cd "$HOME/VirtualBox VMs/${clientname}"
+    VBoxManage modifyvm "${clientname}" \
+        --memory 1024 \
+        --acpi on \
+        --boot1 net \
+        --boot2 none \
```
Comment (dashohoxha) [inline client.sh]: It seems that `--boot2`, `--boot3` etc. are not needed. Try to remove them.

File: client.sh [hunk 3]
```diff
@@ -13,41 +13,49 @@ cat <<-END
...
+        --boot3 none \
+        --boot4 none \
+        --nic1 bridged \
+        --bridgeadapter1 $INTERFACE \
```
Comment (dashohoxha) [inline client.sh]: Where did you get this `$INTERFACE` from?

File: client.sh [hunk 4]
```diff
@@ -13,41 +13,49 @@ cat <<-END
...
+        --nicpromisc1 allow-all 
+    VBoxManage createhd --filename \
+        "$HOME/VirtualBox VMs/${clientname}/${clientname}.vdi" --size 1
+    VBoxManage storagectl "${clientname}" --name "IDE Controller" --add ide
```
Comment (dashohoxha) [inline client.sh]: You don't need a HD for the client. Try to remove these 2 lines.

File: client.sh [hunk 5]
```diff
@@ -13,41 +13,49 @@ cat <<-END
...
- --boot1 net --boot2 none --boot3 none --boot4 none --nic1 bridged\
- --bridgeadapter1 eno1 --nicpromisc1 allow-all
-	VBoxManage createhd --filename "$HOME/VirtualBox VMs/${clientname}/${clientname}.vdi" --size 1
-	VBoxManage storagectl "${clientname}" --name "IDE Controller" --add ide
-	VBoxManage startvm "${clientname}"
+    echo -n "Enter any name for LTSP client : "
+    read clientname
+    echo "Using ${INTERFACE}.."	
+    VBoxManage createvm --name "${clientname}" --register
+    cd "$HOME/VirtualBox VMs/${clientname}"
```
Comment (dashohoxha) [inline client.sh]: Do you really need to `cd`? Try to remove this line.

File: client.sh [hunk 6]
```diff
@@ -13,41 +13,49 @@ cat <<-END
...
+    VBoxManage modifyvm "${clientname}" \
+        --memory 1024 \
```
Comment (dashohoxha) [inline client.sh]: Can you add these options/settings to the command `createvm` (and don't use `modifyvm` at all)?

File: install.sh [hunk 7]
```diff
@@ -27,27 +27,33 @@ ltsp-config lts.conf
 # Creating client image
 ltsp-update-image --cleanup /
 
+# enabling password authentication 
+sed -i /etc/ssh/sshd_config -e \
+    "/^PasswordAuth/ c PasswordAuthentication yes"
```
Comment (dashohoxha) [inline install.sh]: - [x] Move the `-e` switch on the second line.
- [x]  What if PasswordAuthentication is commented (the line starts with a `#`)?

File: install.sh [hunk 8]
```diff
@@ -27,27 +27,33 @@ ltsp-config lts.conf
...
--e "/^#dhcp-range=.*,proxy\$/ c dhcp-range=${NETWORK}.0,proxy"
-	sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
--e "/^#dhcp-range=.*,proxy\$/ c dhcp-range=10.0.2.0,proxy"
+    echo "LTSP server will be in Non-standalone mode of operation"	
+    echo "There is an existing DHCP server running"
+    echo "LTSP server won't provide DHCP services.."
+    sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
+        -e "/^#dhcp-range=.*,proxy\$/ c dhcp-range=${NETWORK}.0,proxy"
+    sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
+        -e "/^#dhcp-range=.*,proxy\$/ c dhcp-range=10.0.2.0,proxy"
```
Comment (dashohoxha) [inline install.sh]: Can you merge these two commands into a single one?

**Comment by dashohoxha** [comment]
The fact that I have to spend 1-2 hours to comment and correct every line that you write is not Ok. But still I don't mind it because I believe that you are trying honestly to do your best. If you did it on purpose it would make me very angry.

> I have tested it multiple time. Also tested it on a friends laptop today.

This shows that even if you test it, there may still be a lot of things to fix and improve.

File: install.sh (hunk 8 above)
Comment (d78ui98) [reply install.sh]: yes.

File: install.sh (hunk 7 above)
Comment (d78ui98) [reply install.sh]: I can use 
`sed -i /etc/ssh/sshd_config -e "/Authentication no\$/ c PasswordAuthentication yes"`
It would handle this case.

File: client.sh (hunk 6 above)
Comment (d78ui98) [reply client.sh]: I did spend some time trying to do this. But when looked at `VBoxManage` help option I saw that `createvm` offered limited functionality. Thats why I will need `modifyvm`
```
createvm                  --name <name>
                            [--groups <group>, ...]
                            [--ostype <ostype>]
                            [--register]
                            [--basefolder <path>]
                            [--uuid <uuid>]
```

File: client.sh (hunk 4 above)
Comment (d78ui98) [reply client.sh]: Yes these lines can be safely removed.

File: client.sh (hunk 3 above)
Comment (d78ui98) [reply client.sh]: I am getting it by using `ip route`
```
INTERFACE=$(ip route | grep -m 1 default | cut -d' ' -f5)
```

**Comment by d78ui98** [comment]
>The fact that I have to spend 1-2 hours to comment and correct every line that you write is not Ok. But still I don't mind it because I believe that you are trying honestly to do your best.

Thank you very much for your time and efforts. Yes I am honestly trying to do my best but I tend to solve problem the complex way. Need to work on that. But, after your efforts I can actually see this code getting much simpler and better. So Thank you again :)

File: install.sh [hunk 9]
```diff
@@ -27,27 +27,32 @@ ltsp-config lts.conf
 # Creating client image
 ltsp-update-image --cleanup /
 
+# enabling password authentication 
+sed -i /etc/ssh/sshd_config \
+    -e "/Authentication no\$/ c PasswordAuthentication yes"
```
Comment (dashohoxha) [inline install.sh:32]: This needs some improvements. But you can do them later.

File: install.sh [hunk 10]
```diff
@@ -27,27 +27,32 @@ ltsp-config lts.conf
...
 if [[ ${STANDALONE,,} == "yes" ]]; then
-	echo "LTSP server will be in standalone mode of operation"	
-	echo "LTSP server will provide DHCP services.."	
-	sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf -e "/192.168.1.0,proxy\$/ \
-c #dhcp-range=${NETWORK}.0,proxy" -e "/10.0.2.0,proxy\$/ c #dhcp-range=10.0.2.0,proxy"
+    echo "LTSP server will be in standalone mode of operation"	
+    echo "LTSP server will provide DHCP services.."	
+    sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
+	-e "/192.168.1.0,proxy\$/ c #dhcp-range=${NETWORK}.0,proxy" \
+	-e "/10.0.2.0,proxy\$/ c #dhcp-range=10.0.2.0,proxy"
```
Comment (dashohoxha) [inline install.sh]: If you comment a line, you don't need to fix the network in it.
These two expressions maybe can be combined into one.

File: install.sh [hunk 11]
```diff
@@ -27,27 +27,32 @@ ltsp-config lts.conf
...
-	sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
--e "/^#dhcp-range=.*,proxy\$/ c dhcp-range=${NETWORK}.0,proxy"
-	sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
--e "/^#dhcp-range=.*,proxy\$/ c dhcp-range=10.0.2.0,proxy"
+    echo "LTSP server will be in Non-standalone mode of operation"	
+    echo "There is an existing DHCP server running"
+    echo "LTSP server won't provide DHCP services.."
+    sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
+        -e "/192.168.1.0,proxy\$/ c dhcp-range=${NETWORK}.0,proxy" \
+        -e "/10.0.2.0,proxy\$/ c dhcp-range=10.0.2.0,proxy"
```
Comment (dashohoxha) [inline install.sh]: This line seems to change nothing. Why it is needed?

File: client.sh [hunk 12]
```diff
@@ -1,53 +1,20 @@
...
-
-
-if [ "$1" == "" ]; then
-  create_client
-fi
-
-if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-  usage
-fi
+VBoxManage createvm --name "${vmname}" --register
```
Comment (dashohoxha) [inline client.sh]: What happens if a vm with the same name already exists?
Maybe you should try to delete it first, before creating it.

**Comment by d78ui98** [comment]
tested both modes of operation. Also tested with the `dhcp`server in the non-standalone mode of operation.

File: install.sh [hunk 13]
```diff
@@ -50,9 +50,6 @@ else
     echo "LTSP server will be in Non-standalone mode of operation"	
     echo "There is an existing DHCP server running"
     echo "LTSP server won't provide DHCP services.."
-    sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
-        -e "/192.168.1.0,proxy\$/ c dhcp-range=${NETWORK}.0,proxy" \
-        -e "/10.0.2.0,proxy\$/ c dhcp-range=10.0.2.0,proxy"
 fi
```
Comment (dashohoxha) [inline install.sh]: This is not what I asked for. I was talking for the last line, you have removed the whole command.
You should understand what you are doing, not follow blindly my instructions (maybe I made a typing mistake).
And you have not tested it (at least not properly).
I am not satisfied with this way of working.

File: client.sh [hunk 14]
```diff
@@ -9,6 +9,10 @@ INTERFACE=$(ip route | grep -m 1 default | cut -d' ' -f5)
 
 vmname=${1:-ltsp-client}
 
+if [ $vmname == "ltsp-client" ]; then
+    VBoxManage unregistervm $vmname --delete
+fi
```
Comment (dashohoxha) [inline client.sh]: Maybe it can be done like this:
`VBoxManage unregistervm $vmname --delete 2>/dev/null`
(without **if**).

File: install.sh [hunk 15]
```diff
@@ -44,8 +44,7 @@ if [[ ${STANDALONE,,} == "yes" ]]; then
     echo "LTSP server will be in standalone mode of operation"	
     echo "LTSP server will provide DHCP services.."	
     sed -i /etc/dnsmasq.d/ltsp-server-dnsmasq.conf \
-	-e "/192.168.1.0,proxy\$/ c #dhcp-range=${NETWORK}.0,proxy" \
-	-e "/10.0.2.0,proxy\$/ c #dhcp-range=10.0.2.0,proxy"
+	-e "/.*,proxy\$/ c #dhcp-range="
```
Comment (dashohoxha) [inline install.sh]: This is not the right way of doing it. If you do it like this why don't you delete it at all? What is the purpose of making it a useless comment.

Comment (d78ui98) [reply install.sh]: Yes you are right.

File: client.sh (hunk 14 above)
Comment (d78ui98) [reply client.sh]: I was also thinking of doing this.

File: install.sh (hunk 13 above)
Comment (d78ui98) [reply install.sh]: Sorrry I was confused by what you meant by line. 
Tests were sucessful as I was using default network address.
Will run another one with different network address.

**Review by dashohoxha — APPROVED** [review]
You can merge it now if you want, and if there are any problems you can fix them later (the same for any possible improvements).
